//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIW_SPAppWeb.HolidayService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfHolidaystringGYyHrpcm", Namespace="http://schemas.datacontract.org/2004/07/FERC.FOL.HolidayService.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PIW_SPAppWeb.HolidayService.HolidayResult))]
    public partial class ResultOfHolidaystringGYyHrpcm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PIW_SPAppWeb.HolidayService.Holiday[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PIW_SPAppWeb.HolidayService.Holiday[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayResult", Namespace="http://schemas.datacontract.org/2004/07/FERC.FOL.HolidayService.Common")]
    [System.SerializableAttribute()]
    public partial class HolidayResult : PIW_SPAppWeb.HolidayService.ResultOfHolidaystringGYyHrpcm {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Holiday", Namespace="http://schemas.datacontract.org/2004/07/FERC.FOL.HolidayService.Common")]
    [System.SerializableAttribute()]
    public partial class Holiday : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Active_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Holiday_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Holiday_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Holiday_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Inactive_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NextFileDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Active_Date {
            get {
                return this.Active_DateField;
            }
            set {
                if ((this.Active_DateField.Equals(value) != true)) {
                    this.Active_DateField = value;
                    this.RaisePropertyChanged("Active_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Holiday_Date {
            get {
                return this.Holiday_DateField;
            }
            set {
                if ((this.Holiday_DateField.Equals(value) != true)) {
                    this.Holiday_DateField = value;
                    this.RaisePropertyChanged("Holiday_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Holiday_Name {
            get {
                return this.Holiday_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Holiday_NameField, value) != true)) {
                    this.Holiday_NameField = value;
                    this.RaisePropertyChanged("Holiday_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Holiday_id {
            get {
                return this.Holiday_idField;
            }
            set {
                if ((this.Holiday_idField.Equals(value) != true)) {
                    this.Holiday_idField = value;
                    this.RaisePropertyChanged("Holiday_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Inactive_Date {
            get {
                return this.Inactive_DateField;
            }
            set {
                if ((this.Inactive_DateField.Equals(value) != true)) {
                    this.Inactive_DateField = value;
                    this.RaisePropertyChanged("Inactive_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NextFileDate {
            get {
                return this.NextFileDateField;
            }
            set {
                if ((this.NextFileDateField.Equals(value) != true)) {
                    this.NextFileDateField = value;
                    this.RaisePropertyChanged("NextFileDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HolidayService.IHolidayService")]
    public interface IHolidayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidays", ReplyAction="http://tempuri.org/IHolidayService/GetHolidaysResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IHolidayService/GetHolidaysStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        PIW_SPAppWeb.HolidayService.HolidayResult GetHolidays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidays", ReplyAction="http://tempuri.org/IHolidayService/GetHolidaysResponse")]
        System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> GetHolidaysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidaysFrom", ReplyAction="http://tempuri.org/IHolidayService/GetHolidaysFromResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IHolidayService/GetHolidaysFromStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        PIW_SPAppWeb.HolidayService.HolidayResult GetHolidaysFrom(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidaysFrom", ReplyAction="http://tempuri.org/IHolidayService/GetHolidaysFromResponse")]
        System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> GetHolidaysFromAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidayDictionary", ReplyAction="http://tempuri.org/IHolidayService/GetHolidayDictionaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IHolidayService/GetHolidayDictionaryStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Collections.Generic.Dictionary<string, int> GetHolidayDictionary(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidayDictionary", ReplyAction="http://tempuri.org/IHolidayService/GetHolidayDictionaryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetHolidayDictionaryAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/getNextBusinessDateWithHolidayList", ReplyAction="http://tempuri.org/IHolidayService/getNextBusinessDateWithHolidayListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IHolidayService/getNextBusinessDateWithHolidayListStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.DateTime getNextBusinessDateWithHolidayList(System.DateTime fromDate, int NumberOfDate, System.Collections.Generic.Dictionary<string, int> holidaydDictionary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/getNextBusinessDateWithHolidayList", ReplyAction="http://tempuri.org/IHolidayService/getNextBusinessDateWithHolidayListResponse")]
        System.Threading.Tasks.Task<System.DateTime> getNextBusinessDateWithHolidayListAsync(System.DateTime fromDate, int NumberOfDate, System.Collections.Generic.Dictionary<string, int> holidaydDictionary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/AddHoliday", ReplyAction="http://tempuri.org/IHolidayService/AddHolidayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IHolidayService/AddHolidayStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        PIW_SPAppWeb.HolidayService.HolidayResult AddHoliday(PIW_SPAppWeb.HolidayService.Holiday holiday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/AddHoliday", ReplyAction="http://tempuri.org/IHolidayService/AddHolidayResponse")]
        System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> AddHolidayAsync(PIW_SPAppWeb.HolidayService.Holiday holiday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/UpdateHoliday", ReplyAction="http://tempuri.org/IHolidayService/UpdateHolidayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IHolidayService/UpdateHolidayStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        PIW_SPAppWeb.HolidayService.HolidayResult UpdateHoliday(PIW_SPAppWeb.HolidayService.Holiday holiday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/UpdateHoliday", ReplyAction="http://tempuri.org/IHolidayService/UpdateHolidayResponse")]
        System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> UpdateHolidayAsync(PIW_SPAppWeb.HolidayService.Holiday holiday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/DeleteHoliday", ReplyAction="http://tempuri.org/IHolidayService/DeleteHolidayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IHolidayService/DeleteHolidayStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        PIW_SPAppWeb.HolidayService.HolidayResult DeleteHoliday(PIW_SPAppWeb.HolidayService.Holiday holiday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/DeleteHoliday", ReplyAction="http://tempuri.org/IHolidayService/DeleteHolidayResponse")]
        System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> DeleteHolidayAsync(PIW_SPAppWeb.HolidayService.Holiday holiday);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHolidayServiceChannel : PIW_SPAppWeb.HolidayService.IHolidayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayServiceClient : System.ServiceModel.ClientBase<PIW_SPAppWeb.HolidayService.IHolidayService>, PIW_SPAppWeb.HolidayService.IHolidayService {
        
        public HolidayServiceClient() {
        }
        
        public HolidayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIW_SPAppWeb.HolidayService.HolidayResult GetHolidays() {
            return base.Channel.GetHolidays();
        }
        
        public System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> GetHolidaysAsync() {
            return base.Channel.GetHolidaysAsync();
        }
        
        public PIW_SPAppWeb.HolidayService.HolidayResult GetHolidaysFrom(System.DateTime start, System.DateTime end) {
            return base.Channel.GetHolidaysFrom(start, end);
        }
        
        public System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> GetHolidaysFromAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetHolidaysFromAsync(start, end);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetHolidayDictionary(System.DateTime start, System.DateTime end) {
            return base.Channel.GetHolidayDictionary(start, end);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetHolidayDictionaryAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetHolidayDictionaryAsync(start, end);
        }
        
        public System.DateTime getNextBusinessDateWithHolidayList(System.DateTime fromDate, int NumberOfDate, System.Collections.Generic.Dictionary<string, int> holidaydDictionary) {
            return base.Channel.getNextBusinessDateWithHolidayList(fromDate, NumberOfDate, holidaydDictionary);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getNextBusinessDateWithHolidayListAsync(System.DateTime fromDate, int NumberOfDate, System.Collections.Generic.Dictionary<string, int> holidaydDictionary) {
            return base.Channel.getNextBusinessDateWithHolidayListAsync(fromDate, NumberOfDate, holidaydDictionary);
        }
        
        public PIW_SPAppWeb.HolidayService.HolidayResult AddHoliday(PIW_SPAppWeb.HolidayService.Holiday holiday) {
            return base.Channel.AddHoliday(holiday);
        }
        
        public System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> AddHolidayAsync(PIW_SPAppWeb.HolidayService.Holiday holiday) {
            return base.Channel.AddHolidayAsync(holiday);
        }
        
        public PIW_SPAppWeb.HolidayService.HolidayResult UpdateHoliday(PIW_SPAppWeb.HolidayService.Holiday holiday) {
            return base.Channel.UpdateHoliday(holiday);
        }
        
        public System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> UpdateHolidayAsync(PIW_SPAppWeb.HolidayService.Holiday holiday) {
            return base.Channel.UpdateHolidayAsync(holiday);
        }
        
        public PIW_SPAppWeb.HolidayService.HolidayResult DeleteHoliday(PIW_SPAppWeb.HolidayService.Holiday holiday) {
            return base.Channel.DeleteHoliday(holiday);
        }
        
        public System.Threading.Tasks.Task<PIW_SPAppWeb.HolidayService.HolidayResult> DeleteHolidayAsync(PIW_SPAppWeb.HolidayService.Holiday holiday) {
            return base.Channel.DeleteHolidayAsync(holiday);
        }
    }
}
